blank_issues_enabled: false
contact_links:
  - name: Questions & discussion
    url: https://github.com/Dev-Devarsh/android_file_transfer_macos/discussions
    about: For general questions, please check Discussions instead of opening an issue.
